### ISSUE TITLE
include Bonsai index annotations in generated asset configs

### ISSUE THREAD

**Issue by jspaleta** [sensu/bonsai-asset-index#153]
Have bonsai include a set of annotations in the generated asset configs that users can use to identify where they got a particular asset config.

We should probably have a discussion concerning the naming convention of the annotations.
But here are my strawman annotations to include:
- sensio.io.bonsai.url -> string
- sensio.io.bonsai.tier -> string
- sensio.io.bonsai.version -> string
- sensio.io.bonsai.tags   -> this a comma delimited string or perhaps a JSON encoded array of strings

Ex output with new annotations:
```
---
type: Asset
api_version: core/v2
metadata:
  name: sensu-plugins-cpu-checks
  namespace: default
  labels: {}
  annotations:
    sensio.io.bonsai.url: "https://bonsai.sensu.io/assets/jspaleta/sensu-plugins-cpu-checks"
    sensio.io.bonsai.tier: "Community"
    sensio.io.bonsai.version: "4.0.0-pre"
    sensio.io.bonsai.tags: "experimental, ruby-runtime"

spec:
  url: https://github.com/jspaleta/sensu-plugins-cpu-checks/releases/download/4.0.0-pre/sensu-plugins-cpu-checks_4.0.0-pre_alpine_linux_amd64.tar.gz
  sha512: 92a57b54b297b5a90011c3472a48c5b4357dbfa123ad391386e6aafe29e6212b6db5da7e4a80514e938361f3030df1ef5022fb99f64e5cc46ed6d8bdc1c7927c
  filters:
  - entity.system.os == 'linux'
  - entity.system.arch == 'amd64'
  - entity.system.platform == 'alpine'

```

**Comment by jspaleta** [comment]
Also i would LOVE to be able to provide an annotation that suggested necessary dependency assets

```
  annotations:
    sensio.io.bonsai.url: "https://bonsai.sensu.io/assets/jspaleta/sensu-plugins-cpu-checks"
    sensio.io.bonsai.tier: "Community"
    sensio.io.bonsai.version: "4.0.0-pre"
    sensio.io.bonsai.suggested_runtime_asset: "https://bonsai.sensu.io/assets/sensu/sensu-ruby-runtime"
    sensio.io.bonsai.suggested_runtime_asset_version: "0.0.5"
    sensio.io.bonsai.tags: "experimental, ruby-runtime"
```

Now in this example i'm treating `runtime` as a very special case and one that exists right now to make the ruby plugins work as assets.   I explicitly state is a suggestion as a breadcrumb for users.

The more general case is that assets can depend on an array of other assets, which is a bit harder.. we'd have to encode that list as a json string packed into a single annotation. That get's complicated and messy.

**Comment by pzupan** [comment]
I've added what I've called common annotations that can be generated from the data.  If you add any key value pair to the  bonsai.yml annotations key, it will be incorporated into the annotations generated on download.

**Comment by jspaleta** [comment]
Just pulled the asset config from:
https://bonsai-asset-index-staging.herokuapp.com/assets/sensu-plugins/sensu-plugins-cpu-checks

### A few problems in the metadata section
1. the sensu.io.bonsai.tags   must be a string or null or it won't parse correctly into sensuctl 
```
the sensu.io.bonsai.tags: []   
```
should read as
```
the sensu.io.bonsai.tags: null   

```
when there are no tags.

2. labels/annotations should read as null if no labels/annotions are defined

```  
labels: []
```
should read as  

```
labels: null
```

3. version is not valid

4. namespace should always be default, the sensu concept of namespace isn't the same as the github user namespace.


### Problems with the spec section

1. asset_url  key should not exist, value there should be reported in the url key

2. last_modified should be an annotation perhaps sensu.io.bonsai.last_modified

**Comment by jspaleta** [comment]
Here's a version of the config with corrections.  Original lines are prefixed with `##`

```
---
type: Asset
api_version: core/v2
metadata:
  name: sensu-plugins-cpu-checks
  ##namespace: sensu-plugins
  namespace: default 
  ##labels: []
  labels: null 
  ##version: 4.0.0
  annotations:
    sensio.io.bonsai.url: https://s3.us-west-2.amazonaws.com/staging.assets.bonsai.sensu.io/68546e739d96fd695655b77b35b5aabfbabeb056/sensu-plugins-cpu-checks_4.0.0_alpine_linux_amd64.tar.gz
    sensio.io.bonsai.tier: Community
    sensio.io.bonsai.version: 4.0.0
    ##sensio.io.bonsai.tags: []
    sensio.io.bonsai.tags: null

spec:
  url: https://github.com/sensu-plugins/sensu-plugins-cpu-checks/releases/download/4.0.0/sensu-plugins-cpu-checks_4.0.0_alpine_linux_amd64.tar.gz
  sha512: b2da25ecd7642e6de41fde37d674fe19dcb6ee3d680e145e32289f7cfc352e6b5f9413ee9b701d61faeaa47b399aa30b25885dbc1ca432c4061c8823774c28f3
  ##asset_url: https://s3.us-west-2.amazonaws.com/staging.assets.bonsai.sensu.io/68546e739d96fd695655b77b35b5aabfbabeb056/sensu-plugins-cpu-checks_4.0.0_alpine_linux_amd64.tar.gz
  ##last_modified: '2019-05-14T17:11:12.000Z'
  filters:
  - entity.system.os == 'linux'
  - entity.system.arch == 'amd64'
  - entity.system.platform == 'alpine'
```
