### ISSUE TITLE
Downloaded asset configs contain incorrect "label" data

### ISSUE THREAD

**Issue by mbiang** [sensu/bonsai-asset-index#183]
The asset configuration file generated by Bonsai from the download modal contains incorrect data in the "label" attribute.   Currently, this is causing the configs to not be usable by sensuctl,

**Expected Behavior**

I expect the generated asset config to look similar this:

```
---
type: Asset
api_version: core/v2
metadata:
  name: sensu-plugins-disk-checks
  labels:
  annotations: 
    bonsai.sensu.io.tags: "tag1, tag2"
spec:
  url: https://assets.bonsai.sensu.io/73a6f8b6f56672630d83ec21676f9a6251094475/sensu-plugins-disk-checks_5.0.0_alpine_linux_amd64.tar.gz
  sha512: 29b8974d17c863a026cc389ba152dd09de4c331eda6c2f295970bf3bb1dac28a85911f17c0804f1b44480f06dde624cdec2773bd6e3db88e3988ddd0b6588862
  filters:
  - entity.system.os == 'linux'
  - entity.system.arch == 'amd64'
  - entity.system.platform == 'alpine'
```

- Annotations are a hash, not a list.
- Bonsai tags are in the annotations section, not the labels section. 
- Note that multiple tags are encased in quotes, and separated by a comma.

**Actual Behavior**

The actual generated asset config from the download modal looks like this:

```
---
type: Asset
api_version: core/v2
metadata:
  name: sensu-plugins-disk-checks
  namespace: default
  labels: ruby-runtime-2.4.4
  annotations: 
spec:
  url: https://assets.bonsai.sensu.io/73a6f8b6f56672630d83ec21676f9a6251094475/sensu-plugins-disk-checks_5.0.0_alpine_linux_amd64.tar.gz
  sha512: 29b8974d17c863a026cc389ba152dd09de4c331eda6c2f295970bf3bb1dac28a85911f17c0804f1b44480f06dde624cdec2773bd6e3db88e3988ddd0b6588862
  filters:
  - entity.system.os == 'linux'
  - entity.system.arch == 'amd64'
  - entity.system.platform == 'alpine'
```

- Example taken from: https://bonsai.sensu.io/assets/sensu-plugins/sensu-plugins-disk-checks
- Annotations are a list, not a hash (can't tell from this example).
- Bonsai tags are in the labels section, not the annotations section.
