### ISSUE TITLE
BugFix: Bonsai Annotations

### ISSUE THREAD

**Issue by jspaleta** [sensu/bonsai-asset-index#216]
1.  Fix sensio to read sensu
2.  Change api_url to point to toplevel api endpoint for asset
3. add namespace and name annotation (or equivalent variable names see example).

## Current Bonsai Generated Confg Example:
```
---
type: Asset
api_version: core/v2
metadata:
  name: sensu-plugins-mysql_centos_amd64
  labels: 
  annotations:
    io.sensio.bonsai.url: https://bonsai.sensu.io/assets/jspaleta/sensu-plugins-mysql
    io.sensio.bonsai.api_url: https://bonsai.sensu.io/api/v1/assets/jspaleta/sensu-plugins-mysql/3.1.7-jef.1/release_asset_builds
    io.sensio.bonsai.tier: Community
    io.sensio.bonsai.version: 3.1.7-jef.1
    io.sensio.bonsai.tags: ''
spec:
  url: https://assets.bonsai.sensu.io/49ee1354285deefe463eb36796e1894bf1509ed3/sensu-plugins-mysql_3.1.7-jef.1_centos_linux_amd64.tar.gz
  sha512: 187af7206dd31bc598ccea8a3b21347e413b7d66c1dc50dfea838601a5f05faa57a8f7fd5aa662e4ba1317d8d376c5da5d0e3f700944906db45ea1eb715330da
  filters:
  - entity.system.os == 'linux'
  - entity.system.arch == 'amd64'
  - entity.system.platform_family == 'rhel'
```

## Proposed Fix
```
---
type: Asset
api_version: core/v2
metadata:
  name: sensu-plugins-mysql_centos_amd64
  labels: 
  annotations:
    io.sensu.bonsai.url: https://bonsai.sensu.io/assets/jspaleta/sensu-plugins-mysql
    io.sensu.bonsai.api_url: https://bonsai.sensu.io/api/v1/assets/jspaleta/sensu-plugins-mysql/
    io.sensu.bonsai.tier: Community
    io.sensu.bonsai.version: 3.1.7-jef.1
    io.sensu.bonsai.namespace: jspaleta
    io.sensu.bonsai.name: sensu-plugins-mysql
    io.sensu.bonsai.tags: ''

spec:
  url: https://assets.bonsai.sensu.io/49ee1354285deefe463eb36796e1894bf1509ed3/sensu-plugins-mysql_3.1.7-jef.1_centos_linux_amd64.tar.gz
  sha512: 187af7206dd31bc598ccea8a3b21347e413b7d66c1dc50dfea838601a5f05faa57a8f7fd5aa662e4ba1317d8d376c5da5d0e3f700944906db45ea1eb715330da
  filters:
  - entity.system.os == 'linux'
  - entity.system.arch == 'amd64'
  - entity.system.platform_family == 'rhel'
```
